### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Rockbard** [kolibril13/blender-spicy-svg#1]
Could not import anything

Tried Blender 4.2.10 - 4.3 -4.5

Error:
Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\enhanced_svg\imports.py", line 259, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\enhanced_svg\imports.py", line 235, in execute
    imported_collection.processed_svg = processed_svg
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Collection' object has no attribute 'processed_svg'

Simpliest SVGs that I tried to import:
![Image](https://github.com/user-attachments/assets/3b6da8e8-d56a-4cf6-bed1-3be796f6edf8)
![Image](https://github.com/user-attachments/assets/fd6c0baa-9e91-4a96-bddd-809c1aeb3043)

**Comment by kolibril13** [comment]
![Image](https://github.com/user-attachments/assets/7c0316bd-5417-4164-a250-7778636eebf5)

thanks for the report!
It works for me without errors, I'm on blender 4.4.3 on a mac.
However, the curve is not filled when imported (unrelated to the error), but this is because of your svg structure, I don't cover all cases. 

The error must be somewhere here in this function:
![Image](https://github.com/user-attachments/assets/c51fd4e9-d981-44e0-bbb5-5e066c590a17)

I can try to create a minimal example for you for debugging in the coming days. Would you be interested in helping to make this work?

**Comment by Rockbard** [comment]
Thanks for the response. 
What would you need me to do?

**Comment by kolibril13** [comment]
with the extension installed, try to run this script:
```py
svg_content = """
<svg class="typst-doc" viewBox="0 0 126.02777777777777 103.4" width="126.02777777777777pt" height="103.4pt" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:h5="http://www.w3.org/1999/xhtml">
    <g>
        <g transform="translate(0 68.55)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gE3DC68D5509581F6B49E9421EB2A2915" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(40.33888888888889 68.55)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gE8020CF8D6D84D2B93C3C10ADA97FC21" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.50277777777778 34.699999999999996)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#g94BA31C14A06A65540BFE5D45C77049F" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.12777777777778 102.85000000000001)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gD5999A55F34C79C37382B148B976B2E7" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.12777777777778 56.050000000000004)">
            <path class="typst-shape" fill="none" stroke="#000000" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 L 22.9 0 "/>
        </g>
    </g>
    <defs id="glyph">
        <symbol id="gE3DC68D5509581F6B49E9421EB2A2915" overflow="visible">
            <path d="M 24.9 7.2000003 C 24.9 7.65 24.65 7.9 24.1 7.9 C 23.7 7.9 23.4 7.55 23.25 6.85 C 22.25 2.9 21.050001 0.90000004 19.7 0.90000004 C 18.85 0.90000004 18.4 1.6 18.4 3 C 18.4 3.65 18.6 4.85 19.050001 6.6 L 21.9 17.85 C 22.15 18.800001 22.25 19.35 22.25 19.6 C 22.25 20.6 21.7 21.1 20.6 21.1 C 19.550001 21.1 18.85 20.5 18.5 19.35 C 17.45 21.2 15.95 22.1 14.05 22.1 C 10.8 22.1 7.9500003 20.45 5.4500003 17.15 C 3.15 14.05 2 10.85 2 7.5 C 2 3.15 4.55 -0.55 8.75 -0.55 C 10.900001 -0.55 13 0.6 15 2.9 C 15.55 1 17.25 -0.55 19.6 -0.55 C 23.050001 -0.55 24.1 3.5 24.9 7.2000003 Z M 17.050001 18.7 C 17.5 17.65 17.75 16.95 17.75 16.5 C 17.75 16.300001 17.7 16.050001 17.65 15.7 L 15.2 6.1 C 15.05 5.55 14.7 4.9500003 14.25 4.35 C 12.400001 2.05 10.6 0.90000004 8.85 0.90000004 C 6.9 0.90000004 5.9 2.4 5.9 5.35 C 5.9 6.55 6.2000003 8.35 6.8 10.75 C 7.85 15 9.35 17.85 11.2 19.4 C 12.2 20.25 13.150001 20.65 14.1 20.65 C 15.45 20.65 16.45 20 17.050001 18.7 Z "/>
        </symbol>
        <symbol id="gE8020CF8D6D84D2B93C3C10ADA97FC21" overflow="visible">
            <path d="M 34.9 18.35 L 4 18.35 C 3.2 18.35 2.8 17.95 2.8 17.2 C 2.8 16.45 3.2 16.050001 4 16.050001 L 34.9 16.050001 C 35.7 16.050001 36.100002 16.45 36.100002 17.2 C 36.100002 17.800001 35.55 18.35 34.9 18.35 Z M 34.9 8.95 L 4 8.95 C 3.2 8.95 2.8 8.55 2.8 7.8 C 2.8 7.05 3.2 6.65 4 6.65 L 34.9 6.65 C 35.7 6.65 36.100002 7.05 36.100002 7.8 C 36.100002 8.45 35.55 8.95 34.9 8.95 Z "/>
        </symbol>
        <symbol id="g94BA31C14A06A65540BFE5D45C77049F" overflow="visible">
            <path d="M 14.05 22.25 C 12.25 22.25 10.45 21.4 8.7 19.7 L 12.150001 33.95 C 12.05 34.4 11.900001 34.7 11.3 34.7 C 9.650001 34.7 6 34.25 5.35 34.2 C 4.6 34.100002 4.2000003 33.75 4.2000003 33 C 4.2000003 32.5 4.65 32.25 5.6 32.25 C 6.55 32.25 7.85 32.3 7.85 31.6 C 7.85 31.4 7.6 30.4 7.15 28.550001 L 3.15 12.45 C 2.6000001 10.35 2.3500001 8.650001 2.3500001 7.4 C 2.3500001 3.1000001 4.65 -0.55 8.75 -0.55 C 12 -0.55 14.85 1.1 17.35 4.4500003 C 19.6 7.55 20.75 10.8 20.75 14.150001 C 20.75 18.5 18.2 22.25 14.05 22.25 Z M 13.95 20.75 C 15.900001 20.75 16.85 19.25 16.85 16.300001 C 16.85 14.95 16.550001 13.150001 15.95 10.900001 C 14.85 6.65 13.400001 3.75 11.650001 2.2 C 10.650001 1.35 9.7 0.95 8.75 0.95 C 6.7000003 0.95 5.7000003 2.55 5.7000003 5.75 C 5.7000003 6.85 5.9500003 8.5 6.4500003 10.7 L 7.55 15.2 C 7.7000003 15.95 7.9500003 16.5 8.25 16.9 C 10.2 19.45 12.1 20.75 13.95 20.75 Z "/>
        </symbol>
        <symbol id="gD5999A55F34C79C37382B148B976B2E7" overflow="visible">
            <path d="M 16.4 16.25 C 16.4 15 17.050001 14.35 18.4 14.35 C 20.2 14.35 21.35 15.900001 21.35 17.7 C 21.35 20.5 18.4 22.1 15.400001 22.1 C 11.95 22.1 8.8 20.6 6.1 17.65 C 3.4 14.7 2.05 11.45 2.05 7.9500003 C 2.05 3.05 5.3 -0.55 10.2 -0.55 C 12.85 -0.55 15.2 0.1 17.25 1.35 C 18.95 2.4 20.2 3.45 21 4.5 C 21.35 4.9500003 21.5 5.3 21.5 5.4500003 C 21.5 6 21.25 6.3 20.7 6.3 C 20.45 6.3 20.2 6.1 19.9 5.7000003 C 18.25 3.5 16.2 2.1000001 13.85 1.5 C 12.3 1.1 11.150001 0.90000004 10.3 0.90000004 C 7.4500003 0.90000004 6.05 2.65 6.05 6.1 C 6.05 9.2 7.5 13.7 8.7 15.85 C 9.900001 18.050001 12.45 20.65 15.400001 20.65 C 17.300001 20.65 18.6 20.1 19.300001 19.050001 C 17.75 18.9 16.4 17.9 16.4 16.25 Z "/>
        </symbol>
    </defs>
</svg>
"""

import bpy
import sys
import tempfile
from pathlib import Path

temp_dir = Path(tempfile.gettempdir())
# temp_dir = Path.cwd()
svg_file = temp_dir / "temp.svg"

svg_file.write_text(svg_content)
bpy.ops.import_curve.svg(filepath=str(svg_file))

from enhanced_svg.svg_preprocessing import preprocess_svg
svg_file.write_text(preprocess_svg(svg_content))

import bpy
from mathutils import Matrix


def latest_collection_set_position(position=(0, 0, 0)):
    collection = bpy.context.collection.children[-1]
    for obj in collection.objects:
        obj.data.transform(Matrix.Scale(100, 4))
        obj.location = position


latest_collection_set_position((0, 1, 0))
```

and you should get this scene:

![Image](https://github.com/user-attachments/assets/4a2c0f15-612a-41af-bc1d-fbc1492e38c9)

**Comment by Rockbard** [comment]
I'm getting an error on Blender 4.4.3
Tried to reinstall the addon with no luck.

Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ModuleNotFoundError: No module named 'enhanced_svg'

**Comment by kolibril13** [comment]
hi there, I'll try to find some time the next days looking into this, but can't promise anything.

**Comment by kolibril13** [comment]
Just did some digging, I think 
`from bl_ext.blender_org.enhanced_svg.svg_preprocessing import preprocess_svg`
might do the trick.
Can you run this code?

```py
svg_content = """
<svg class="typst-doc" viewBox="0 0 126.02777777777777 103.4" width="126.02777777777777pt" height="103.4pt" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:h5="http://www.w3.org/1999/xhtml">
    <g>
        <g transform="translate(0 68.55)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gE3DC68D5509581F6B49E9421EB2A2915" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(40.33888888888889 68.55)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gE8020CF8D6D84D2B93C3C10ADA97FC21" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.50277777777778 34.699999999999996)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#g94BA31C14A06A65540BFE5D45C77049F" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.12777777777778 102.85000000000001)">
            <g class="typst-text" transform="scale(1, -1)">
                <use xlink:href="#gD5999A55F34C79C37382B148B976B2E7" x="0" fill="#000000" fill-rule="nonzero"/>
            </g>
        </g>
        <g transform="translate(98.12777777777778 56.050000000000004)">
            <path class="typst-shape" fill="none" stroke="#000000" stroke-width="2.4" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="4" d="M 0 0 L 22.9 0 "/>
        </g>
    </g>
    <defs id="glyph">
        <symbol id="gE3DC68D5509581F6B49E9421EB2A2915" overflow="visible">
            <path d="M 24.9 7.2000003 C 24.9 7.65 24.65 7.9 24.1 7.9 C 23.7 7.9 23.4 7.55 23.25 6.85 C 22.25 2.9 21.050001 0.90000004 19.7 0.90000004 C 18.85 0.90000004 18.4 1.6 18.4 3 C 18.4 3.65 18.6 4.85 19.050001 6.6 L 21.9 17.85 C 22.15 18.800001 22.25 19.35 22.25 19.6 C 22.25 20.6 21.7 21.1 20.6 21.1 C 19.550001 21.1 18.85 20.5 18.5 19.35 C 17.45 21.2 15.95 22.1 14.05 22.1 C 10.8 22.1 7.9500003 20.45 5.4500003 17.15 C 3.15 14.05 2 10.85 2 7.5 C 2 3.15 4.55 -0.55 8.75 -0.55 C 10.900001 -0.55 13 0.6 15 2.9 C 15.55 1 17.25 -0.55 19.6 -0.55 C 23.050001 -0.55 24.1 3.5 24.9 7.2000003 Z M 17.050001 18.7 C 17.5 17.65 17.75 16.95 17.75 16.5 C 17.75 16.300001 17.7 16.050001 17.65 15.7 L 15.2 6.1 C 15.05 5.55 14.7 4.9500003 14.25 4.35 C 12.400001 2.05 10.6 0.90000004 8.85 0.90000004 C 6.9 0.90000004 5.9 2.4 5.9 5.35 C 5.9 6.55 6.2000003 8.35 6.8 10.75 C 7.85 15 9.35 17.85 11.2 19.4 C 12.2 20.25 13.150001 20.65 14.1 20.65 C 15.45 20.65 16.45 20 17.050001 18.7 Z "/>
        </symbol>
        <symbol id="gE8020CF8D6D84D2B93C3C10ADA97FC21" overflow="visible">
            <path d="M 34.9 18.35 L 4 18.35 C 3.2 18.35 2.8 17.95 2.8 17.2 C 2.8 16.45 3.2 16.050001 4 16.050001 L 34.9 16.050001 C 35.7 16.050001 36.100002 16.45 36.100002 17.2 C 36.100002 17.800001 35.55 18.35 34.9 18.35 Z M 34.9 8.95 L 4 8.95 C 3.2 8.95 2.8 8.55 2.8 7.8 C 2.8 7.05 3.2 6.65 4 6.65 L 34.9 6.65 C 35.7 6.65 36.100002 7.05 36.100002 7.8 C 36.100002 8.45 35.55 8.95 34.9 8.95 Z "/>
        </symbol>
        <symbol id="g94BA31C14A06A65540BFE5D45C77049F" overflow="visible">
            <path d="M 14.05 22.25 C 12.25 22.25 10.45 21.4 8.7 19.7 L 12.150001 33.95 C 12.05 34.4 11.900001 34.7 11.3 34.7 C 9.650001 34.7 6 34.25 5.35 34.2 C 4.6 34.100002 4.2000003 33.75 4.2000003 33 C 4.2000003 32.5 4.65 32.25 5.6 32.25 C 6.55 32.25 7.85 32.3 7.85 31.6 C 7.85 31.4 7.6 30.4 7.15 28.550001 L 3.15 12.45 C 2.6000001 10.35 2.3500001 8.650001 2.3500001 7.4 C 2.3500001 3.1000001 4.65 -0.55 8.75 -0.55 C 12 -0.55 14.85 1.1 17.35 4.4500003 C 19.6 7.55 20.75 10.8 20.75 14.150001 C 20.75 18.5 18.2 22.25 14.05 22.25 Z M 13.95 20.75 C 15.900001 20.75 16.85 19.25 16.85 16.300001 C 16.85 14.95 16.550001 13.150001 15.95 10.900001 C 14.85 6.65 13.400001 3.75 11.650001 2.2 C 10.650001 1.35 9.7 0.95 8.75 0.95 C 6.7000003 0.95 5.7000003 2.55 5.7000003 5.75 C 5.7000003 6.85 5.9500003 8.5 6.4500003 10.7 L 7.55 15.2 C 7.7000003 15.95 7.9500003 16.5 8.25 16.9 C 10.2 19.45 12.1 20.75 13.95 20.75 Z "/>
        </symbol>
        <symbol id="gD5999A55F34C79C37382B148B976B2E7" overflow="visible">
            <path d="M 16.4 16.25 C 16.4 15 17.050001 14.35 18.4 14.35 C 20.2 14.35 21.35 15.900001 21.35 17.7 C 21.35 20.5 18.4 22.1 15.400001 22.1 C 11.95 22.1 8.8 20.6 6.1 17.65 C 3.4 14.7 2.05 11.45 2.05 7.9500003 C 2.05 3.05 5.3 -0.55 10.2 -0.55 C 12.85 -0.55 15.2 0.1 17.25 1.35 C 18.95 2.4 20.2 3.45 21 4.5 C 21.35 4.9500003 21.5 5.3 21.5 5.4500003 C 21.5 6 21.25 6.3 20.7 6.3 C 20.45 6.3 20.2 6.1 19.9 5.7000003 C 18.25 3.5 16.2 2.1000001 13.85 1.5 C 12.3 1.1 11.150001 0.90000004 10.3 0.90000004 C 7.4500003 0.90000004 6.05 2.65 6.05 6.1 C 6.05 9.2 7.5 13.7 8.7 15.85 C 9.900001 18.050001 12.45 20.65 15.400001 20.65 C 17.300001 20.65 18.6 20.1 19.300001 19.050001 C 17.75 18.9 16.4 17.9 16.4 16.25 Z "/>
        </symbol>
    </defs>
</svg>
"""

import bpy
import sys
import tempfile
from pathlib import Path

temp_dir = Path(tempfile.gettempdir())
# temp_dir = Path.cwd()
svg_file = temp_dir / "temp.svg"

svg_file.write_text(svg_content)
bpy.ops.import_curve.svg(filepath=str(svg_file))

from bl_ext.blender_org.enhanced_svg.svg_preprocessing import preprocess_svg
svg_file.write_text(preprocess_svg(svg_content))

import bpy
from mathutils import Matrix


def latest_collection_set_position(position=(0, 0, 0)):
    collection = bpy.context.collection.children[-1]
    for obj in collection.objects:
        obj.data.transform(Matrix.Scale(100, 4))
        obj.location = position


latest_collection_set_position((0, 1, 0))

**Comment by Rockbard** [comment]
I got this message

 Python: Traceback (most recent call last):
  File "\Text", line 71, in <module>
  File "\Text", line 65, in latest_collection_set_position
IndexError: bpy_prop_collection[-1]: out of range.

**Comment by kolibril13** [comment]
That's already one step closer to the goal! :)

Can you first delete all collections in the scene and run it again?

Or just delete this part,
```
def latest_collection_set_position(position=(0, 0, 0)):
    collection = bpy.context.collection.children[-1]
    for obj in collection.objects:
        obj.data.transform(Matrix.Scale(100, 4))
        obj.location = position


latest_collection_set_position((0, 1, 0))
```
this is just scaling the collection, so you probably have to zoom in a bit until you can see the objects without these lines.

**Comment by Rockbard** [comment]
Yep, it works in both suggested ways.

**Comment by kolibril13** [comment]
Great! Then I suggest you import your SVGs using the script above.
I could also look into fixing the `imported_collection.processed_svg = processed_svg` error — but that would take around 2 hours, and since you’re the only one affected and there’s now a working workaround, it doesn’t seem necessary.

**Comment by Rockbard** [comment]
It wasn't crucial from the get-go.
I think I could wait until the next update.

Thanks a lot!

**Comment by notbyhalf** [comment]
Hi there, I'm experiencing the same error on macos Sequoia (M1 Macbook Pro) and Blender 4.4.3

> imported_collection.processed_svg = processed_svg

I've read through the conversation above but I'm not sure I follow whether there is a fix.

**Comment by kolibril13** [comment]
hi @notbyhalf , I just updated the extension, can you check if it's fixed in the latest version?
https://extensions.blender.org/add-ons/enhanced-svg/

**Comment by notbyhalf** [comment]
> hi [@notbyhalf](https://github.com/notbyhalf) , I just updated the extension, can you check if it's fixed in the latest version? https://extensions.blender.org/add-ons/enhanced-svg/

Hi @kolibril13 – that seems to be working as expected now. Thank you so much. 

A note for other readers, I updated the Extension in Blender (as it was already installed) and it still presented with the same error. Tried again this morning and it works. I believe it was necessary to restart Blender after updating the Extension.

**Comment by Rockbard** [comment]
Hey, guys.
Can you check one more file for me as it does not get imported as expected? 
Basically, I'm just getting the hollow curves.

This one is from Xara, I'm trying to import it in Blender 4.5
SVGs from Inkscape importing as it should, but not this one.

![Image](https://github.com/user-attachments/assets/484987d8-49eb-4d1c-83b8-b728e33d76a3)

**Comment by kolibril13** [comment]
Hi @Rockbard, 
this would take me probably a few hours to investigate, but my scedule is currently quite packed.
Sorry!

**Comment by Rockbard** [comment]
No worries, take your time. 
 No rush at all.
